/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SalesOutreachRouteImport } from './routes/sales-outreach'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PilotProgramRouteImport } from './routes/pilot-program'
import { Route as CustomerSupportRouteImport } from './routes/customer-support'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BackOfficeOperationsRouteImport } from './routes/back-office-operations'
import { Route as AiHumanSupportRouteImport } from './routes/ai-human-support'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOutreachRoute = SalesOutreachRouteImport.update({
  id: '/sales-outreach',
  path: '/sales-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotProgramRoute = PilotProgramRouteImport.update({
  id: '/pilot-program',
  path: '/pilot-program',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/customer-support',
  path: '/customer-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeOperationsRoute = BackOfficeOperationsRouteImport.update({
  id: '/back-office-operations',
  path: '/back-office-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHumanSupportRoute = AiHumanSupportRouteImport.update({
  id: '/ai-human-support',
  path: '/ai-human-support',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-human-support': typeof AiHumanSupportRoute
  '/back-office-operations': typeof BackOfficeOperationsRoute
  '/contact': typeof ContactRoute
  '/customer-support': typeof CustomerSupportRoute
  '/pilot-program': typeof PilotProgramRoute
  '/pricing': typeof PricingRoute
  '/sales-outreach': typeof SalesOutreachRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-human-support': typeof AiHumanSupportRoute
  '/back-office-operations': typeof BackOfficeOperationsRoute
  '/contact': typeof ContactRoute
  '/customer-support': typeof CustomerSupportRoute
  '/pilot-program': typeof PilotProgramRoute
  '/pricing': typeof PricingRoute
  '/sales-outreach': typeof SalesOutreachRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-human-support': typeof AiHumanSupportRoute
  '/back-office-operations': typeof BackOfficeOperationsRoute
  '/contact': typeof ContactRoute
  '/customer-support': typeof CustomerSupportRoute
  '/pilot-program': typeof PilotProgramRoute
  '/pricing': typeof PricingRoute
  '/sales-outreach': typeof SalesOutreachRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-human-support'
    | '/back-office-operations'
    | '/contact'
    | '/customer-support'
    | '/pilot-program'
    | '/pricing'
    | '/sales-outreach'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-human-support'
    | '/back-office-operations'
    | '/contact'
    | '/customer-support'
    | '/pilot-program'
    | '/pricing'
    | '/sales-outreach'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/ai-human-support'
    | '/back-office-operations'
    | '/contact'
    | '/customer-support'
    | '/pilot-program'
    | '/pricing'
    | '/sales-outreach'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiHumanSupportRoute: typeof AiHumanSupportRoute
  BackOfficeOperationsRoute: typeof BackOfficeOperationsRoute
  ContactRoute: typeof ContactRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  PilotProgramRoute: typeof PilotProgramRoute
  PricingRoute: typeof PricingRoute
  SalesOutreachRoute: typeof SalesOutreachRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-outreach': {
      id: '/sales-outreach'
      path: '/sales-outreach'
      fullPath: '/sales-outreach'
      preLoaderRoute: typeof SalesOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-program': {
      id: '/pilot-program'
      path: '/pilot-program'
      fullPath: '/pilot-program'
      preLoaderRoute: typeof PilotProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-support': {
      id: '/customer-support'
      path: '/customer-support'
      fullPath: '/customer-support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office-operations': {
      id: '/back-office-operations'
      path: '/back-office-operations'
      fullPath: '/back-office-operations'
      preLoaderRoute: typeof BackOfficeOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-human-support': {
      id: '/ai-human-support'
      path: '/ai-human-support'
      fullPath: '/ai-human-support'
      preLoaderRoute: typeof AiHumanSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiHumanSupportRoute: AiHumanSupportRoute,
  BackOfficeOperationsRoute: BackOfficeOperationsRoute,
  ContactRoute: ContactRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  PilotProgramRoute: PilotProgramRoute,
  PricingRoute: PricingRoute,
  SalesOutreachRoute: SalesOutreachRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
